# Path to your oh-my-zsh configuration.
ZSH=$HOME/.dotfiles/zsh/modules/oh-my-zsh
ZSH_THEME="amuse"

# Set to this to use case-sensitive completion
CASE_SENSITIVE="true"
DISABLE_AUTO_UPDATE="true"
HIST_STAMPS="mm/dd/yyyy"

# Load the oh-my-zsh shell framework here and include the source file
source "$ZSH/oh-my-zsh.sh"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(git python tmux)

# load our own completion functions
fpath=(~/.dotfiles/zsh/completion $fpath)

# completion
autoload -U compinit
compinit

# Load any command aliases if they exist
if [ -e "$HOME/.dotfiles/zsh/aliases" ]; then
    source "$HOME/.dotfiles/zsh/aliases"
fi

# expand functions in the prompt
setopt prompt_subst

# ignore duplicate history entries
setopt histignoredups

# makes color constants available
autoload -U colors
colors

export CLICOLOR=1
PS1='[%{$fg_bold[green]%}%n@%m %{$fg_bold[blue]%}%~%{$reset_color%}]
$ '

# Manually set the language environment we're running. In most
# cases this should default to a unicode font.
export LANG=en_US.UTF-8

# Load the ZSH environment file if we have it. The default
# version of this file will attempt to rewrite the PS1
# variable with a GIT friendly version if possible.
if [ -e "$HOME/.dotfiles/zsh/zshenv" ]; then
   source "$HOME/.dotfiles/zsh/zshenv"
fi

# Preferred editor for local and remote sessions
# Use vim as the default editor
if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='vim'
else
   export EDITOR='mvim'
fi
