# Path to your oh-my-zsh configuration.
export ZSH_ROOT="$HOME/.dotfiles/zsh"
export ZSH="$ZSH_ROOT/modules/oh-my-zsh"

# Set to this to use case-sensitive completion
export CASE_SENSITIVE="true"
export DISABLE_AUTO_UPDATE="true"
export HIST_STAMPS="mm/dd/yyyy"

# ZSH Plugins list. These are found in the oh-my-zsh modules directory
plugins=(git python tmux)

# load our own completion functions
fpath=($ZSH_ROOT/completion $fpath)

# Load the oh-my-zsh shell framework here and include the source file
source "$ZSH/oh-my-zsh.sh"

# completion
autoload -U compinit
compinit

# Load any command aliases if they exist
if [ -e "$ZSH_ROOT/aliases" ]; then
    source "$ZSH_ROOT/aliases"
fi

# expand functions in the prompt
setopt prompt_subst

# ignore duplicate history entries
setopt histignoredups

# makes color constants available
autoload -U colors
colors

export CLICOLOR=1
PS1='[%{$fg_bold[green]%}%n@%m %{$fg_bold[blue]%}%~%{$reset_color%}]
$ '

# Manually set the language environment we're running. In most
# cases this should default to a unicode font.
export LANG=en_US.UTF-8

# Load the ZSH environment file if we have it. The default
# version of this file will attempt to rewrite the PS1
# variable with a GIT friendly version if possible.
if [ -e "$ZSH_ROOT/zshenv" ]; then
   source "$ZSH_ROOT/zshenv"
fi

# Preferred editor for local and remote sessions
# Use vim as the default editor
export EDITOR="vim"
